title: Default Page

sections:
  pages: true
  fields:
    fields:
      data:
        type: blocks
        fieldsets:
          text:
            label: Text
            type: group
            fieldsets:
              - heading
              - text
              - list
          media:
            label: Media
            type: group
            fieldsets:
              - image
              - video
          code:
            label: Code
            type: group
            open: false
            fieldsets:
              - code
              - markdown

